use_frameworks!

platform :ios, '9.0'

target 'JIMultiSlideShowView_Example' do
  pod 'JIMultiSlideShowView', :path => '../'

  target 'JIMultiSlideShowView_Tests' do
    inherit! :search_paths

    
  end
end
